; generated by lcc-xr18NW $Version: 5.0 - XR18NW $ on Fri Apr 14 12:13:58 2017

SP:	equ	2 ;stack pointer
memAddr: equ	14
retAddr: equ	6
retVal:	equ	15
regArg1: equ	12
regArg2: equ	13
	listing off
	include lcc1802proloNW.inc
	listing on
_PIN4:
	db 0
;$$function start$$ _boydinc
_boydinc:		;framesize=2
;void boydinc(){
;	asm(" include \"boydscan.inc\"\n");
 include "boydscan.inc"
;}
L1:
	Cretn

;$$function end$$ _boydinc
;$$function start$$ _disp1
_disp1:		;framesize=2
;void disp1(unsigned char d){//display a byte as two hex digits
;	asm(" glo 12\n ani 0x0f\n" //prep bottom digit
 glo 12
 ani 0x0f
 dec 2
 str 2
 out 7
 glo 12
 shr
 shr
 shr
 shr
 dec 2
 str 2
 out 7
;}
L3:
	Cretn

;$$function end$$ _disp1
;$$function start$$ _dispmemloc
_dispmemloc:		;framesize=14
	pushr R4
	pushr R5
	pushr R6
	pushr R7
	reserve 4; save room for outgoing arguments
	st2 R12,'O',sp,(14+1); flag1 
;void dispmemloc(unsigned int loc){
;	register unsigned char* m=0;
	ldaD R7,0; reg:acon
;	initleds();
;	disp1(m[loc+1]);
 req
 seq
 dec 2
 out 7
 req
	ld2 R11,'O',sp,(14+1) ;reg:INDIRU2(addr)
	incm R11,1
	alu2 R11,R11,R7,add,adc	;ADDP2(reg,reg)
	ld1 R12,'O',R11,0
	zExt R12 ;CVUI2: widen unsigned char to signed int (zero extend)
	Ccall _disp1
;	disp1(m[loc]);
	ld2 R11,'O',sp,(14+1) ;reg:INDIRU2(addr)
	alu2 R11,R11,R7,add,adc	;ADDP2(reg,reg)
	ld1 R12,'O',R11,0
	zExt R12 ;CVUI2: widen unsigned char to signed int (zero extend)
	Ccall _disp1
;	disp1(loc&0xff);
	ld2 R11,'O',sp,(14+1) ;reg:INDIRU2(addr)
	alu2I R11,R11,255,ani,ani ;removed copy;BANDU2(reg,con)  
	cpy1 R12,R11
	zExt R12 ;CVUI2(reg)*: widen unsigned char to signed int (zero extend)*
	Ccall _disp1
;	disp1(loc>>8);
	ld2 R11,'O',sp,(14+1) ;reg:INDIRU2(addr)
	shrU2I R11,8
	cpy1 R12,R11
	zExt R12 ;CVUI2(reg)*: widen unsigned char to signed int (zero extend)*
	Ccall _disp1
;}
L5:
	release 4; release room for outgoing arguments
	popr R7
	popr R6
	popr R5
	popr R4
	Cretn

;$$function end$$ _dispmemloc
;$$function start$$ _dispval
_dispval:		;framesize=8
	pushr R7
	reserve 4; save room for outgoing arguments
	st2 R12,'O',sp,(8+1); flag1 
	ldA2 R11,'O',sp,(8+1); reg:addr
	ld2 R10,'O',sp,(8+1) ;reg:INDIRI2(addr)
	str1 R10,R11; ASGNU1(indaddr,reg)		DH
;void dispval(unsigned char v){
;	initleds();
;	disp1(v);
 req
 seq
 dec 2
 out 7
 req
	ld1 R12,'O',sp,(8+1)
	zExt R12 ;CVUI2: widen unsigned char to signed int (zero extend)
	Ccall _disp1
;	for (i=6;i!=0;i--) out(7,0);
	ldaD R7,6; reg:acon
	lbr L12
L9:
	ldaD R12,7; reg:acon
	ld2z R13
	Ccall _out; CALLI2(ar)
L10:
	decm R7,1	;SUBU2(reg,consm)
L12:
	jnzU2 R7,L9; NE 0 
;}
L7:
	release 4; release room for outgoing arguments
	popr R7
	Cretn

;$$function end$$ _dispval
;$$function start$$ _getsp
_getsp:		;framesize=2
;unsigned int getsp(){//return stack pointer value
;	asm(" cpy2 r15,sp\n"  	//copy stack pointer to return reg
;	return 0;				//not executed
 cpy2 r15,sp
 cretn
	ld2z R15
L13:
	Cretn

;$$function end$$ _getsp
;$$function start$$ _execute
_execute:		;framesize=14
	reserve 2; save room for local variables
	pushr R5
	pushr R6
	pushr R7
	reserve 4; save room for outgoing arguments
	cpy2 R7,R12; function(2054) 1
;void execute(unsigned int loc){
;	unsigned char* mem=0;
	ldaD R6,0; reg:acon
;		dispval(0x44); delay(250);
	ldaD R12,68; reg:acon
	Ccall _dispval
	ldaD R12,250; reg:acon
	Ccall _delay
;		dispmemloc(loc); delay(3000);
	cpy2 R12,R7 ;LOADU2*(reg)
	Ccall _dispmemloc
	ldaD R12,3000; reg:acon
	Ccall _delay
;		op=mem[loc]; val=mem[loc+1];
	ldA2 R11,'O',sp,(11+1); reg:addr
	alu2 R10,R7,R6,add,adc	;ADDP2(reg,reg)
	ldn1 R10,R10;reg:  INDIRU1(indaddr)
	str1 R10,R11; ASGNU1(indaddr,reg)		DH
	ldA2 R11,'O',sp,(10+1); reg:addr
	cpy2 R10,R7
	incm R10,1
	alu2 R10,R10,R6,add,adc	;ADDP2(reg,reg)
	ldn1 R10,R10;reg:  INDIRU1(indaddr)
	str1 R10,R11; ASGNU1(indaddr,reg)		DH
;		switch (op){
	ld1 R5,'O',sp,(11+1)
	zExt R5 ;CVUI2: widen unsigned char to signed int (zero extend)
	jcI2I R5,0,lbnf,L16  ;LT=lbnf i.e. subtract immedB from A and jump if borrow
	jnI2I R5,4,lbnf,L16; GT reverse  the subtraction
	cpy2 R11,R5
	shl2I R11,1
	ld2 R11,'O',R11,(L24) ;reg:INDIRP2(addr)
	jumpv R11; JUMPV(reg)
L24:
	dw L19
	dw L20
	dw L21
	dw L22
	dw L23
L19:
;				dispval(0x49); delay(250);
	ldaD R12,73; reg:acon
	Ccall _dispval
	ldaD R12,250; reg:acon
	Ccall _delay
;				dispval(mem[val+4096]); delay(1000);
	ld1 R11,'O',sp,(10+1)
	zExt R11 ;CVUI2: widen unsigned char to signed int (zero extend)
	ldA2 R11,'O',R11,(4096); reg:addr
	alu2 R11,R11,R6,add,adc	;ADDP2(reg,reg)
	ld1 R12,'O',R11,0
	zExt R12 ;CVUI2: widen unsigned char to signed int (zero extend)
	Ccall _dispval
	ldaD R12,1000; reg:acon
	Ccall _delay
;				dispval(0x50); delay(250);
	ldaD R12,80; reg:acon
	Ccall _dispval
	ldaD R12,250; reg:acon
	Ccall _delay
;				break;
	lbr L17
L20:
;				mem[val+4096]+=1;
	ld1 R11,'O',sp,(10+1)
	zExt R11 ;CVUI2: widen unsigned char to signed int (zero extend)
	ldA2 R11,'O',R11,(4096); reg:addr
	alu2 R11,R11,R6,add,adc	;ADDP2(reg,reg)
	ld1 R10,'O',R11,0
	zExt R10 ;CVUI2: widen unsigned char to signed int (zero extend)
	incm R10,1
	str1 R10,R11; ASGNU1(indaddr,reg)		DH
;				break;
	lbr L17
L21:
;				loc=val+4096-2; //ugh
	ld1 R11,'O',sp,(10+1)
	zExt R11 ;CVUI2: widen unsigned char to signed int (zero extend)
	ldA2 R11,'O',R11,(4096); reg:addr
	decm R11,2	;SUBI2(reg,consm)
	cpy2 R7,R11 ;LOADU2*(reg)
;				break;
	lbr L17
L22:
;				delay(val*4);
	ld1 R11,'O',sp,(10+1)
	zExt R11 ;CVUI2: widen unsigned char to signed int (zero extend)
	shl2I R11,2
	cpy2 R12,R11 ;LOADU2*(reg)
	Ccall _delay
;				break;
	lbr L17
L23:
;				dispval(getsp());
	Ccall _getsp;CALLU2(ar)*
	cpy1 R11,R15;LOADU1(reg)
	cpy1 R12,R11
	zExt R12 ;CVUI2(reg)*: widen unsigned char to signed int (zero extend)*
	Ccall _dispval
;				delay(250);
	ldaD R12,250; reg:acon
	Ccall _delay
;				break;
	lbr L17
L16:
;				dispval(0x41); delay(250);
	ldaD R12,65; reg:acon
	Ccall _dispval
	ldaD R12,250; reg:acon
	Ccall _delay
;				dispmemloc(loc); delay(5000);
	cpy2 R12,R7 ;LOADU2*(reg)
	Ccall _dispmemloc
	ldaD R12,5000; reg:acon
	Ccall _delay
;				break;
L17:
;		loc+=2;
	incm R7,2
;}
L15:
	release 4; release room for outgoing arguments
	popr R7
	popr R6
	popr R5
	release 2; release room for local variables 
	Cretn

;$$function end$$ _execute
;$$function start$$ _main
_main:		;framesize=18
	reserve 4; save room for local variables
	pushr R4
	pushr R5
	pushr R6
	pushr R7
	reserve 4; save room for outgoing arguments
;{
;	unsigned int loc=0;
	ld2z R5
;	unsigned char memtype='o'; //displaying o=eeprom,a=ram
	ldaD R4,111; reg:acon
;	register unsigned char* mem=0;
	ldaD R7,0; reg:acon
;	dispval(0x42);
	ldaD R12,66; reg:acon
	Ccall _dispval
;	delay(1000);
	ldaD R12,1000; reg:acon
	Ccall _delay
	lbr L27
L26:
;	while(1){
;		dispmemloc(loc);
	cpy2 R12,R5 ;LOADU2*(reg)
	Ccall _dispmemloc
;		k=boydscan();
	Ccall _boydscan; CALLI2(ar)
	cpy2 R11,R15 ;LOADU2*(reg)
	cpy1 R6,R11;LOADU1(reg)
;		switch(k){
	cpy1 R11,R6
	zExt R11 ;CVUI2(reg)*: widen unsigned char to signed int (zero extend)*
	st2 R11,'O',sp,(13+1); ASGNI2(addr,reg)
	ld2 R11,'O',sp,(13+1) ;reg:INDIRI2(addr)
	jcI2I R11,16,lbnf,L29  ;LT=lbnf i.e. subtract immedB from A and jump if borrow
	jnI2I R11,20,lbnf,L29; GT reverse  the subtraction
	shl2I R11,1
	ld2 R11,'O',R11,(L39-32) ;reg:INDIRP2(addr)
	jumpv R11; JUMPV(reg)
L39:
	dw L32
	dw L33
	dw L34
	dw L37
	dw L38
L32:
;				loc +=1;
	incm R5,1
;				break;
	lbr L30
L33:
;				loc -=1;
	decm R5,1	;SUBU2(reg,consm)
;				break;
	lbr L30
L34:
;				if (memtype=='o'){
	jneU1I R4,111,L35	; DH 4
;					loc=4096;
	ldaD R5,4096; reg:acon
;					memtype='a';
	ldaD R4,97; reg:acon
;				}else{
	lbr L30
L35:
;					loc=0;
	ld2z R5
;					memtype='o';
	ldaD R4,111; reg:acon
;				}
;				break;
	lbr L30
L37:
;				dispmemloc(loc); //makes a blink
	cpy2 R12,R5 ;LOADU2*(reg)
	Ccall _dispmemloc
;				k=boydscan(); dispval(k); delay(250);
	Ccall _boydscan; CALLI2(ar)
	cpy2 R11,R15 ;LOADU2*(reg)
	cpy1 R6,R11;LOADU1(reg)
	cpy1 R12,R6
	zExt R12 ;CVUI2(reg)*: widen unsigned char to signed int (zero extend)*
	Ccall _dispval
	ldaD R12,250; reg:acon
	Ccall _delay
;				k2=boydscan(); dispval(k2); delay(250);
	Ccall _boydscan; CALLI2(ar)
	ldA2 R10,'O',sp,(15+1); reg:addr
	cpy2 R11,R15 ;LOADU2*(reg)
	str1 R11,R10; ASGNU1(indaddr,reg)		DH
	ld1 R12,'O',sp,(15+1)
	zExt R12 ;CVUI2: widen unsigned char to signed int (zero extend)
	Ccall _dispval
	ldaD R12,250; reg:acon
	Ccall _delay
;				mem[loc]=(k<<4)+k2;
	alu2 R11,R5,R7,add,adc	;ADDP2(reg,reg)
	cpy1 R10,R6
	zExt R10 ;CVUI2(reg)*: widen unsigned char to signed int (zero extend)*
	shl2I R10,4
	ld1 R9,'O',sp,(15+1)
	zExt R9 ;CVUI2: widen unsigned char to signed int (zero extend)
	alu2 R10,R10,R9,add,adc; ADDI2(r,r)
	str1 R10,R11; ASGNU1(indaddr,reg)		DH
;				break;
	lbr L30
L38:
;				loc=4096;
	ldaD R5,4096; reg:acon
;				dispval(0x45);
	ldaD R12,69; reg:acon
	Ccall _dispval
;				delay(250);
	ldaD R12,250; reg:acon
	Ccall _delay
;				execute(4096);
	ldaD R12,4096; reg:acon
	Ccall _execute
;				break;
	lbr L30
L29:
;				dispval(k);
	cpy1 R12,R6
	zExt R12 ;CVUI2(reg)*: widen unsigned char to signed int (zero extend)*
	Ccall _dispval
;				delay(250);
	ldaD R12,250; reg:acon
	Ccall _delay
;		}
L30:
;	}
L27:
;	while(1){
	lbr L26
;}
L25:
	release 4; release room for outgoing arguments
	popr R7
	popr R6
	popr R5
	popr R4
	release 4; release room for local variables 
	Cretn

;$$function end$$ _main
;$$function start$$ _delay
_delay:		;framesize=10
	pushr R6
	pushr R7
	reserve 4; save room for outgoing arguments
	cpy2 R7,R12; function(2054) 1
;void delay(unsigned int howlong){
;	for (i=1;i!=howlong;i++){
	ldaD R6,1; reg:acon
	lbr L45
L42:
;		oneMs();
	Ccall _oneMs; CALLI2(ar)
;	}
L43:
;	for (i=1;i!=howlong;i++){
	incm R6,1
L45:
	jneU2 R6,R7,L42; NE
;}
L41:
	release 4; release room for outgoing arguments
	popr R7
	popr R6
	Cretn

;$$function end$$ _delay
;$$function start$$ _olduinoincluder
_olduinoincluder:		;framesize=2
;void olduinoincluder(){
;	asm("\tinclude olduino.inc\n");
	include olduino.inc
;}
L46:
	Cretn

;$$function end$$ _olduinoincluder
	include lcc1802epiloNW.inc
	include IO1802.inc
