; generated by lcc-xr18NW $Version: 5.0 - XR18NW $ on Fri Apr 07 15:33:49 2017

SP:	equ	2 ;stack pointer
memAddr: equ	14
retAddr: equ	6
retVal:	equ	15
regArg1: equ	12
regArg2: equ	13
	listing off
	include lcc1802proloNW.inc
	listing on
_PIN4:
	db 0
_text:
	db 1
	db 8
	db 0
	db 5
_banner:
	db 15
	db 15
	db 15
	db 15
	db 5
	db 0
	db 8
	db 1
	db 15
;$$function start$$ _texttext
_texttext:		;framesize=8
	pushr R7
	reserve 4; save room for outgoing arguments
	st2 R12,'O',sp,(8+1); flag1 
;void texttext(int n){
;	initleds();
;	for (i=n; i>0;i--){
 req
 seq
 dec 2
 out 7
 req
	ld2 R11,'O',sp,(8+1) ;reg:INDIRI2(addr)
	cpy2 R7,R11 ;LOADU2*(reg)
	lbr L6
L3:
;		out(7,text[i-1]);
	ldaD R12,7; reg:acon
	cpy2 R11,R7	;SUBU2(reg,consm)
	decm R11,1	;SUBU2(reg,consm)
	ld1 R13,'O',R11,(_text)
	zExt R13 ;CVUI2: widen unsigned char to signed int (zero extend)
	Ccall _out; CALLI2(ar)
;	}
L4:
;	for (i=n; i>0;i--){
	decm R7,1	;SUBU2(reg,consm)
L6:
	jnzU2 R7,L3; NE 0 
;}
L1:
	release 4; release room for outgoing arguments
	popr R7
	Cretn

;$$function end$$ _texttext
;$$function start$$ _main
_main:		;framesize=10
	pushr R6
	pushr R7
	reserve 4; save room for outgoing arguments
;{
;	initleds();
;		" ldad r11,_banner\n"
;	delay(1000);
 req
 seq
 dec 2
 out 7
 req
 ldad r11,_banner
 ldad r10,8
 sex 11
 out 7
 out 7
 out 7
 out 7
 out 7
 out 7
 out 7
 out 7
 sex 2
	ldaD R12,1000; reg:acon
	Ccall _delay
;	texttext(1);
	ldaD R12,1; reg:acon
	Ccall _texttext
;	delay(1000);
	ldaD R12,1000; reg:acon
	Ccall _delay
;	texttext(2);
	ldaD R12,2; reg:acon
	Ccall _texttext
L10:
;	while(1);
L11:
	lbr L10
	lbr L14
L13:
;	while(1){
;		for(start=7;start>=0;start--){ //#digits
	ldaD R7,7; reg:acon
L16:
;			initleds();
;			for(loc=start;loc<8;loc++){
 req
 seq
 dec 2
 out 7
 req
	cpy2 R6,R7 ;LOADI2(reg)
	lbr L24
L21:
;				out(7,banner[loc]);
	ldaD R12,7; reg:acon
	ld1 R13,'O',R6,(_banner)
	zExt R13 ;CVUI2: widen unsigned char to signed int (zero extend)
	Ccall _out; CALLI2(ar)
;				delay(100);
	ldaD R12,100; reg:acon
	Ccall _delay
;			}
L22:
;			for(loc=start;loc<8;loc++){
	incm R6,1
L24:
	jcI2I R6,8,lbnf,L21  ;LT=lbnf i.e. subtract immedB from A and jump if borrow
;			delay(1000);
	ldaD R12,1000; reg:acon
	Ccall _delay
;		}
L17:
;		for(start=7;start>=0;start--){ //#digits
	decm R7,1	;SUBI2(reg,consm)
	jcI2I R7,0,lbdf,L16; GE is flipped test from LT
;	}
L14:
;	while(1){
	lbr L13
;}
L7:
	release 4; release room for outgoing arguments
	popr R7
	popr R6
	Cretn

;$$function end$$ _main
;$$function start$$ _delay
_delay:		;framesize=10
	pushr R6
	pushr R7
	reserve 4; save room for outgoing arguments
	cpy2 R7,R12; function(2054) 1
;void delay(unsigned int howlong){
;	for (i=1;i!=howlong;i++){
	ldaD R6,1; reg:acon
	lbr L29
L26:
;		oneMs();
	Ccall _oneMs; CALLI2(ar)
;	}
L27:
;	for (i=1;i!=howlong;i++){
	incm R6,1
L29:
	jneU2 R6,R7,L26; NE
;}
L25:
	release 4; release room for outgoing arguments
	popr R7
	popr R6
	Cretn

;$$function end$$ _delay
;$$function start$$ _olduinoincluder
_olduinoincluder:		;framesize=2
;void olduinoincluder(){
;	asm("\tinclude olduino.inc\n");
	include olduino.inc
;}
L30:
	Cretn

;$$function end$$ _olduinoincluder
	include lcc1802epiloNW.inc
	include IO1802.inc
