; generated by lcc-xr18DH $Version: 5.0 - XR18DH $ on Tue Jan 24 14:35:32 2017

SP:	equ	2 ;stack pointer
memAddr: equ	14
retAddr: equ	6
retVal:	equ	15
regArg1: equ	12
regArg2: equ	13
	listing off
	include lcc1802proloDH.inc
	listing on
_main: ;copt is peeping your size 4 frame with oct 23 rules
	reserve 2
;void main(){
;	if (x=0)
	ld2z R11 
	st2I 0,'O',sp,(0); ASGNI2(addr,acon)
	MESSAGE "ASSIGNMENT USED AS COMPARISON OPERATOR? - IS THAT WHAT YOU WANTED?"
	jzU2 R11,L2; EQ 0 
;		x++;
	cpy2 memaddr,sp	;opt19
	ldn2 R11,memaddr
	incm R11,1
	st2 R11,'O',sp,(0); ASGNI2(addr,reg)
L2:
;}
L1:
	release 2
	Cretn

	include lcc1802epiloDH.inc
	include IO1802.inc
