; generated by lcc-xr182b $Version: 5.0 - XR182b $ on Tue Jun 25 17:04:20 2013

SP:	equ	2 ;stack pointer
memAddr: equ	14
retAddr: equ	6
retVal:	equ	15
regArg1: equ	12
regArg2: equ	13
	listing off
	include lcc1802ProloFL.inc
	listing on
	include lcc1802Epilofl.inc
	include IO1802.inc
