; generated by lcc-xr182b $Version: 5.0 - XR182b $ on Tue Jun 25 16:51:36 2013

SP:	equ	2 ;stack pointer
memAddr: equ	14
retAddr: equ	6
retVal:	equ	15
regArg1: equ	12
regArg2: equ	13
	listing off
	include lcc1802ProloFL.inc
	listing on
_PIN4:
	db 0
L2:
	db 2 dup (0); zerofill global
_mysetqOn:
	reserve 2
	release 2
	Cretn

L8:
	db 2 dup (0); zerofill global
_main:
	reserve 2
	release 2
	Cretn

L16:
	db 2 dup (0); zerofill global
_delay:
	pushr r7
	reserve 4; save room for outgoing arguments
	cpy2 r7,r12; function(2054) 1
	release 4; release room for outgoing arguments
	popr r7
	Cretn

L25:
	db 2 dup (0); zerofill global
_olduinoincluder:
	reserve 2
	release 2
	Cretn

L29:
	db 111
	db 108
	db 100
	db 117
	db 105
	db 110
	db 111
	db 105
	db 110
	db 99
	db 108
	db 117
	db 100
	db 101
	db 114
	db 35
	db 48
	db 120
	db 37
	db 100
	db 32
	db 114
	db 101
	db 116
	db 117
	db 114
	db 110
	db 101
	db 100
	db 10
	db 0
L27:
	db 111
	db 108
	db 100
	db 117
	db 105
	db 110
	db 111
	db 105
	db 110
	db 99
	db 108
	db 117
	db 100
	db 101
	db 114
	db 35
	db 48
	db 120
	db 37
	db 100
	db 40
	db 41
	db 32
	db 99
	db 97
	db 108
	db 108
	db 101
	db 100
	db 10
	db 0
L23:
	db 100
	db 101
	db 108
	db 97
	db 121
	db 35
	db 48
	db 120
	db 37
	db 100
	db 32
	db 114
	db 101
	db 116
	db 117
	db 114
	db 110
	db 101
	db 100
	db 10
	db 0
L18:
	db 100
	db 101
	db 108
	db 97
	db 121
	db 35
	db 48
	db 120
	db 37
	db 100
	db 40
	db 104
	db 111
	db 119
	db 108
	db 111
	db 110
	db 103
	db 61
	db 48
	db 120
	db 37
	db 120
	db 41
	db 32
	db 99
	db 97
	db 108
	db 108
	db 101
	db 100
	db 10
	db 0
L14:
	db 109
	db 97
	db 105
	db 110
	db 35
	db 48
	db 120
	db 37
	db 100
	db 32
	db 114
	db 101
	db 116
	db 117
	db 114
	db 110
	db 101
	db 100
	db 10
	db 0
L10:
	db 109
	db 97
	db 105
	db 110
	db 35
	db 48
	db 120
	db 37
	db 100
	db 40
	db 41
	db 32
	db 99
	db 97
	db 108
	db 108
	db 101
	db 100
	db 10
	db 0
L6:
	db 109
	db 121
	db 115
	db 101
	db 116
	db 113
	db 79
	db 110
	db 35
	db 48
	db 120
	db 37
	db 100
	db 32
	db 114
	db 101
	db 116
	db 117
	db 114
	db 110
	db 101
	db 100
	db 10
	db 0
L4:
	db 109
	db 121
	db 115
	db 101
	db 116
	db 113
	db 79
	db 110
	db 35
	db 48
	db 120
	db 37
	db 100
	db 40
	db 41
	db 32
	db 99
	db 97
	db 108
	db 108
	db 101
	db 100
	db 10
	db 0
	include lcc1802Epilofl.inc
	include IO1802.inc
